/**
 * Объектная модель. API.
 * This is a sample Object Model.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Модель
 */
export interface Model {
    /**
     * Идентификатор модели
     */
    id: string;
    /**
     * Наименование модели
     */
    name: string;
    /**
     * Код типа модели
     */
    modelTypeCode: number;
    /**
     * Описание
     */
    description?: string;
}
